settings:
  legacy:
    force: false
    interval: 0s
server:
  status: true
  open: true
  port: 5001
  host: "localhost"
schema:
- name: /Users/emcniece/Code/go/src/raenv
  path: /Users/emcniece/Code/go/src/raenv
  commands:
    vet:
      status: true
    fmt:
      status: true
    install:
      status: true
    build:
      status: true
    run:
      status: true
  watcher:
    paths:
    - /
    extensions:
    - go
    ignored_paths:
    - .git
    - .realize
    - vendor
